resource_group_name         = "poc_my_terraform_rg"
resource_group_location     = "poc_West Europe"
virtual_network_name        = "poc_vnetprod019"
subnet_name                 = "poc_subnet019"
public_ip_name              = "poc_publicip019"
network_security_group_name = "poc_nsgprod019"
network_interface_name      = "poc_nicprod019"
linux_virtual_machine_name  = "poc_linuxvm019"